zookeeper:
  image: wurstmeister/zookeeper
  ports:
    - "2181:2181"
kafka:
  image: wurstmeister/kafka:0.8.2.0
  ports:
    - "9092:9092"
  links:
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: 192.168.59.103
  volumes:
      - /var/run/docker.sock:/var/run/docker.sock
mongodb:
  image: mongo:2.6.7
  ports:
    - "27017:27017"
    - "28017:28017"
  command: mongod --rest
  environment:
    - MONGO_URL=mongodb://mongodb:27017
